CREATE  TABLE IF NOT EXISTS `AppUser` (
  `ID` INT NOT NULL ,
  `name` VARCHAR(64) NULL ,
  PRIMARY KEY (`ID`) ,
  CONSTRAINT `FK_AppUser__User`
    FOREIGN KEY (`ID` )
    REFERENCES `User` (`ID` )
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB